[project]
name = "my-marimos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.2",
    "marimo>=0.14.16",
    "pyarrow>=21.0.0",
    "sqlglot>=27.6.0",
]
